from django.urls import path
from app_modules.order.views import (
    AssignDriverOrderView,
    AssignedDriverOrderDataTableAjaxPagination,
    OrderCreateView,
    GetCustomersProductsAjax,
    GetCustomerDetailsAjax,
    GetProductUnitTypesAjax,
    AddProductDetailsInOrderListAjax,
    GetProductPriceStockAjax,
    OrderListView,
    OrderListAjax,
    OrderBillListAjax,
    OrderLogDatatableAjaxView,
    OrderTablePrintAjaxView,
    OrderUpdateView,
    AjaxGetUpdateOrderProductDetails,
    GetProductForOrderByBarcodeAjax,
    GetWarehouseProductsAjax,
    CarCreateView,
    CarListView,
    CarDataTableAjaxPagination,
    CarUpdateView,
    CarDeleteAjaxView,
    OrderLogAjaxView,
    OrderLogAjaxView,
    PlanRouteAjaxView,
    DriverAssignRoutesAjax,
    AssignedDriverOrderList,
    OrderDetailView,
    OrderPackingView,
    RenderOptimizedMap,
    SetOrderProductPackingDetailAjaxView,
    DetailViewAssignDriverOrderView,
    SetOrderShippedAjaxView,
    OrderCancelAjaxView,
    AssignDriverRoutesCreateView,
    LoadDriverAjaxView,
    SetOrderUndeliveredAjaxView,
    DetailViewAssignDriverOrderForCompleteView,
    DriverAssignRoutesOrderStatusAjax,
    DetailViewAssignDriverOrderForCancelView,
    SetOrderCompletedAjaxView,
    BrandSearchAjaxView,
    OrderSearchAjaxView,
    ProductSearchAjaxView,
    AddReplacementProductAjaxView,
    GenerateBillAjaxView,
    DispatchOrderListView,
    GenerateBillView,
    PrintDispatchRoutesView,
    OrderBillListView,
    TransferStockView,
    StockDetailAjaxView,
    UpdateProductAjaxView,
    SetInformAdminReplacement,
    ReplacementProductAjaxView,
    CompleteReplacementAjaxView,
    FetchShortestRouteView,

)

app_name = "order"

urlpatterns = [
    path("type/<str:type>/create/",OrderCreateView.as_view(),name="order_create"),
    path("<int:pk>/details/", OrderDetailView.as_view(), name="order_detail"),
    path("<int:pk>/packing/", OrderPackingView.as_view(), name="order_packing"),
    path("car-create/", CarCreateView.as_view(), name="car_create"),
    path("car-list/", CarListView.as_view(), name="car_list"),
    path("car-list-ajax/", CarDataTableAjaxPagination.as_view(), name="car_list_ajax"),
    path("car/<int:pk>/update/", CarUpdateView.as_view(), name="car_update"),
    path("car-delete/", CarDeleteAjaxView.as_view(), name="car_delete"),
    path("ajax-get-customers-products/", GetCustomersProductsAjax.as_view(),name="get_customers_products_ajax"),
    path("ajax-get-customer-details/", GetCustomerDetailsAjax.as_view(),name="get_customer_details_ajax"),
    path("ajax-get-product-unit-type/", GetProductUnitTypesAjax.as_view(), name = "ajax_get_product_unit_type" ),
    path("ajax-get-product-price-stock/", GetProductPriceStockAjax.as_view(), name = "ajax_get_product_price_stock" ),
    path("ajax-add-product-details-in-order-list/",AddProductDetailsInOrderListAjax.as_view(),name="ajax_add_product_details_in_order_list"),
    path("",OrderListView.as_view(),name="order_list"),
    path("bills/", OrderBillListView.as_view(),name="order_bill_list"),
    path("draft-orders/",OrderListView.as_view(),name="draft_order_list"),
    path("dispatch/",DispatchOrderListView.as_view(),name="dispatch_order_list"),
    
    path("ajax-order-list/",OrderListAjax.as_view(),name="order_list_ajax"),
    path("ajax-order-bill-list/",OrderBillListAjax.as_view(),name="order_bill_list_ajax"),
    path("type/<str:type>/<int:pk>/update",OrderUpdateView.as_view(),name="order_update"),
    path("ajax-get-update-order-product-details/",AjaxGetUpdateOrderProductDetails.as_view(),name="ajax_get_update_order_product_details"),
    path("ajax-get-product-for-order-by-barcode/",GetProductForOrderByBarcodeAjax.as_view(),name="ajax_get_product_for_order_by_barcode"),
    path("ajax-get-warehouse-products",GetWarehouseProductsAjax.as_view(),name="get_warehouse_products_ajax"),
    path('<int:pk>/order-log-list-ajax/', OrderLogAjaxView.as_view(), name='order_log_ajax'),
    path('order-log-list-ajax-datatable/', OrderLogDatatableAjaxView.as_view(), name='order_log_ajax_datatable'),
    path('order-table-print-ajax', OrderTablePrintAjaxView.as_view(), name='order_table_print_ajax'),
    path('<int:pk>/generate-bill/', GenerateBillView.as_view(), name='generate_bill'),
    path('order-assign-driver', AssignDriverOrderView.as_view(), name='assign_driver'),
    path('plan-route-ajax', PlanRouteAjaxView.as_view(), name='plan_route_ajax'),
    path('driver-assigned-route-ajax', DriverAssignRoutesAjax.as_view(), name='assign_route'),
    path('driver-assigned-route-status-ajax', DriverAssignRoutesOrderStatusAjax.as_view(), name='order_route_status_complete'),
    
    path("assigned-driver-order-list/",AssignedDriverOrderList.as_view(),name="assigned_order_driver_list"),
    path("assigned-driver-route-create/",AssignDriverRoutesCreateView.as_view(),name="assigned_driver_route_create"),
    path("assigned-driver-route-create/load-driver",LoadDriverAjaxView.as_view(),name="load_driver"),

    path("transfer-stock/", TransferStockView.as_view(), name="transfer_stock"),
    path("stock/details/", StockDetailAjaxView.as_view(), name="stock_details"),
    path("update/product/", UpdateProductAjaxView.as_view(), name="update_order_product"),
    path("replacement-products-list-ajax/", ReplacementProductAjaxView.as_view(), name="replacement_product_list"),
    path("replacement/complete/", CompleteReplacementAjaxView.as_view(), name="set_replacement_complete"),

    path("assigned-driver-order-ajax/",AssignedDriverOrderDataTableAjaxPagination.as_view(),name="assign_driver_order_ajax"),
    path("<int:assigned_route>/render-optimize-route-map/",RenderOptimizedMap.as_view(),name="render_optimize_route_map"),

    path("<int:assigned_route>/detail-assigned-order/",DetailViewAssignDriverOrderView.as_view(),name="detail_assigned_order"),
    path("<int:assigned_route>/detail-assigned-order-complete/",DetailViewAssignDriverOrderForCompleteView.as_view(),name="detail_assigned_order_complete"),
    path("<int:assigned_route>/detail-assigned-order-cancel/",DetailViewAssignDriverOrderForCancelView.as_view(),name="detail_assigned_order_cancel"),
    
    path("<int:assigned_route>/detail-assigned-order-location/",RenderOptimizedMap.as_view(),name="detail_assigned_order_location"),
    
    path('set-order-product-packing-detail', SetOrderProductPackingDetailAjaxView.as_view(), name='set_order_product_packing_detail'),
    path('set-order-shipped', SetOrderShippedAjaxView.as_view(), name='set_order_shipped'),
    path('set-order-undelivered', SetOrderUndeliveredAjaxView.as_view(), name='set_order_undelivered'),
    path('set-order-completed', SetOrderCompletedAjaxView.as_view(), name='set_order_completed'),
    path('cancel-order', OrderCancelAjaxView.as_view(), name='cancel_order'),

    path("brand/search/", BrandSearchAjaxView.as_view(), name="brand_search"),
    path("order/search/", OrderSearchAjaxView.as_view(), name="order_search"),
    path("order-product/search/", ProductSearchAjaxView.as_view(), name="order_product_search"),

    path("replacement/product/add/", AddReplacementProductAjaxView.as_view(), name="add_replacement_product"),
    path("print/dispatch-routes/<int:pk>", PrintDispatchRoutesView.as_view(), name="print_dispatch_routes"),
    path("set-inform-admin-for-replacement", SetInformAdminReplacement.as_view(), name="set_inform_admin_for_replacement"),

    path("generate/bill/<str:type>", GenerateBillAjaxView.as_view(), name="generate_bill_form"),
    path('fetch_shortest_route/', FetchShortestRouteView.as_view(), name='fetch_shortest_route'),
]