# Generated by Django 4.1.7 on 2024-09-19 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('customers', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('credit_type', models.CharField(choices=[('app credit', 'App Credit'), ('walk in credit', 'Walk-in Credit'), ('web credit', 'Web Credit')], default='web credit', max_length=20, verbose_name='Credit Type')),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('decline', 'Decline')], default='new', max_length=10, verbose_name='Status')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('item_total', models.FloatField(default=0, verbose_name='Item Total')),
                ('grand_total', models.FloatField(default=0, verbose_name='Grand Total')),
                ('adjustment', models.FloatField(default=0, verbose_name='Adjustment')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_credit_memos', to='company.company', verbose_name='Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditMemoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit_type', models.CharField(max_length=50, verbose_name='Unit Type')),
                ('return_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('fresh_return_quantity', models.PositiveIntegerField(default=0, verbose_name='Fresh Quantity')),
                ('damage_return_quantity', models.PositiveIntegerField(default=0, verbose_name='Damage Quantity')),
                ('total_pieces', models.PositiveIntegerField(default=0, verbose_name='Total Pieces')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Total Price')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='Unit Price')),
                ('credit_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_memo_products', to='credit_memo.creditmemo', verbose_name='Credit Memo')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_credit_memo', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditMemoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.TextField(verbose_name='Remark')),
                ('credit_memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_memo.creditmemo', verbose_name='Credit Memo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Credit Memo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
