# Generated by Django 4.1.7 on 2024-09-19 03:57

import app_modules.customers.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('credit_memo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('discount_a', models.FloatField(blank=True, default=0, null=True, verbose_name='Discount A (%)')),
                ('discount_b', models.FloatField(blank=True, default=0, null=True, verbose_name='Discount B (%)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_company', to='company.company', verbose_name='Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('csv_file', models.FileField(upload_to='csv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('genericname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Generic Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Product Code')),
                ('product_image', models.ImageField(upload_to='product-images', verbose_name='Product Image')),
                ('is_apply_ml_quantity', models.BooleanField(default=False, verbose_name='Is Apply ML Quantity')),
                ('ml_quantity', models.FloatField(default=0.0, verbose_name='ML Quantity')),
                ('is_apply_weight', models.BooleanField(default=False, verbose_name='Is Apply Weight (OZ)')),
                ('weight', models.FloatField(default=0.0, verbose_name='Weight (Oz)')),
                ('srp', models.FloatField(blank=True, null=True, verbose_name='SRP(Suggested Retail Price)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=False, max_length=10, verbose_name='Status')),
                ('is_type_a_invoice', models.BooleanField(default=False, verbose_name='Is Type A Invoice')),
                ('box', models.BooleanField(default=False, verbose_name='Box')),
                ('box_piece', models.IntegerField(default=0, verbose_name='Pieces in Box')),
                ('case', models.BooleanField(default=False, verbose_name='Case')),
                ('case_piece', models.IntegerField(default=0, verbose_name='Pieces in Case')),
                ('mrp', models.FloatField(default=0.0, verbose_name='MRP')),
                ('wholesale_rate', models.FloatField(default=0.0, verbose_name='Wholesale Rate')),
                ('retail_rate', models.FloatField(default=0.0, verbose_name='Retail  Rate')),
                ('purchase_price', models.FloatField(default=0.0, verbose_name='Purchase Price')),
                ('cost_price', models.FloatField(default=0.0, verbose_name='Cost Price')),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='product.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_company', to='company.company', verbose_name='Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=1000, unique=True, verbose_name='Vehicle name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vehicle_set', to='company.company', verbose_name='Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseProductStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('before_stock', models.PositiveIntegerField(default=0, verbose_name='Before Stock(Pieces)')),
                ('affected_stock', models.IntegerField(default=0, verbose_name='Affected Stock(Pieces)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Current Stock(Pieces)')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_history', to='product.product', verbose_name='Product')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_history_set', to='product.productvehicle')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock_history', to='company.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock(Pieces)')),
                ('ready_for_dispatch', models.PositiveIntegerField(default=0, verbose_name='Ready for Dispatch Stock(Pieces)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='product.product', verbose_name='Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='company.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.TextField(verbose_name='Remark')),
                ('before_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Before Stock(Pieces)')),
                ('affected_stock', models.IntegerField(blank=True, null=True, verbose_name='Affected Stock(Pieces)')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Stock(Pieces)')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Action By')),
                ('credit_memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_memo.creditmemo', verbose_name='Credit Memo')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_set', to='product.productvehicle'),
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_type', models.CharField(max_length=10, verbose_name='Product Type')),
                ('barcode_number', models.CharField(max_length=255, unique=True)),
                ('barcode_code', models.FileField(upload_to='product-barcode', validators=[app_modules.customers.validators.validate_file_extension])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_barcode', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
