# Generated by Django 4.1.7 on 2024-09-19 03:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDriverRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Route Name')),
                ('date', models.DateField(verbose_name='Deliver Date')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancel', 'Cancel')], default='pending', max_length=50, verbose_name='Status')),
                ('synchronized_route', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assign_routes', to='users.driver', verbose_name='Driver')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.warehouse', verbose_name='Start Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Order ID')),
                ('item_total', models.FloatField(blank=True, null=True, verbose_name='Gross Bill Total')),
                ('shipping_charges', models.FloatField(blank=True, null=True, verbose_name='Shipping Charges')),
                ('packing_charges', models.FloatField(blank=True, null=True, verbose_name='Packing Charges')),
                ('adjustments', models.FloatField(blank=True, default=0, null=True, verbose_name='Adjustments')),
                ('use_credits', models.FloatField(blank=True, default=0, null=True, verbose_name='Use Credits')),
                ('grand_total', models.FloatField(blank=True, default=0, null=True, verbose_name='Grand Total')),
                ('paid_amount', models.FloatField(blank=True, default=0, null=True, verbose_name='Paid Amount')),
                ('balance_amount', models.FloatField(blank=True, default=0, null=True, verbose_name='Balance Amount')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=30, null=True, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dispatch', 'Dispatch'), ('new', 'New'), ('cancel', 'Cancel'), ('completed', 'Completed')], default='new', max_length=25, verbose_name='Status')),
                ('internal_remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal Remark')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Order Date')),
                ('reference_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Reference Number')),
                ('is_bill_generated', models.BooleanField(default=False, verbose_name='Is Bill Generated')),
                ('shipping_address_line_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1 ')),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2 ')),
                ('shipping_city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('shipping_state', models.CharField(blank=True, max_length=30, null=True, verbose_name='State')),
                ('shipping_country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('shipping_zip_code', models.IntegerField(blank=True, null=True, verbose_name='Zip Code')),
                ('billing_address_line_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 1')),
                ('billing_address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2')),
                ('billing_city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('billing_state', models.CharField(blank=True, max_length=30, null=True, verbose_name='State')),
                ('billing_country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('billing_zip_code', models.IntegerField(blank=True, null=True, verbose_name='Zip Code')),
                ('product_reference', models.JSONField(blank=True, null=True)),
                ('inform_admin_for_settlement', models.BooleanField(default=False, verbose_name='Inform Admin For Settlement')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_orders', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created BY')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customers', to='customers.customer')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_orders', to='company.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.TextField(verbose_name='Remark')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Action By')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_logs', to='order.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit_type', models.CharField(default='piece', max_length=50, verbose_name='Unit Type')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price_type', models.CharField(blank=True, choices=[('mrp', 'MRP'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], default='mrp', max_length=50, null=True, verbose_name='Price Type')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Unit Price')),
                ('product_discount1', models.FloatField(blank=True, default=0, null=True, verbose_name='Product Discount 1')),
                ('product_discount2', models.FloatField(blank=True, default=0, null=True, verbose_name='Product Discount 2')),
                ('packed_quantity', models.PositiveIntegerField(default=0, verbose_name='Packed Quantity')),
                ('unpacked_quantity', models.PositiveIntegerField(default=0, verbose_name='Unpacked Quantity')),
                ('special_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='Special Rate')),
                ('special_discount', models.FloatField(blank=True, default=0, null=True, verbose_name='Special Discount')),
                ('free_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Free Quantity')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_local_bill', models.BooleanField(default=True, verbose_name='Is Local Bill')),
                ('slip_no', models.IntegerField(blank=True, null=True, verbose_name='Slip No')),
                ('bill_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bill No')),
                ('bill_date', models.DateField(blank=True, null=True, verbose_name='Bill Date')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Bill Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Paid Amount')),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Due Amount')),
                ('gr_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gr_date', models.DateField(blank=True, null=True, verbose_name='G.R. Date')),
                ('transporter', models.CharField(blank=True, max_length=100, null=True)),
                ('case_number', models.IntegerField(blank=True, null=True, verbose_name='Case No')),
                ('packed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('written_by', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_pdf', models.FileField(blank=True, null=True, upload_to='sales-bills/%Y/%m/%d/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_bill', to='customers.customer', verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_bill', to='order.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('car_nickname', models.CharField(max_length=30, verbose_name='Car Nick Name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('licence_plate', models.CharField(max_length=20, verbose_name='Licence Plate')),
                ('start_mileage', models.CharField(max_length=50, verbose_name='Start Mileage')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('make', models.CharField(max_length=30, verbose_name='Make')),
                ('vin_number', models.IntegerField(verbose_name='VIN Number')),
                ('inspect_exp_date', models.DateField(default=datetime.date.today, verbose_name='Inspect. Exp Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_company', to='company.company', verbose_name='Company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignOrderRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True, verbose_name='stop')),
                ('remark', models.CharField(blank=True, max_length=120, null=True, verbose_name='Remark')),
                ('driver_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_driver_routes', to='order.assigndriverroutes', verbose_name='Assigned Driver Routes')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assined_orders', to='order.order', verbose_name='Assigned Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
