# Generated by Django 4.1.7 on 2024-09-19 03:57

import app_modules.customers.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('company', '0001_initial'),
        # ('order', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer_name', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('customer_type', models.CharField(choices=[('distributor', 'Distributor'), ('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=255, verbose_name='Customer Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=255, verbose_name='Status')),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax Id')),
                ('terms', models.CharField(blank=True, choices=[('case', 'Case'), ('check', 'Check'), ('net 10', 'Net 10'), ('net 15', 'Net 15'), ('net 30', 'Net 30')], max_length=255, null=True, verbose_name='Terms')),
                ('dba_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='DBA Name')),
                ('store_open_time', models.TimeField(blank=True, null=True, verbose_name='Store Open Time')),
                ('store_close_time', models.TimeField(blank=True, null=True, verbose_name='Store Close Time')),
                ('total_credit_amount', models.FloatField(default=0, verbose_name='Total Credit Amount')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('transport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transport')),
                ('cst', models.CharField(blank=True, max_length=255, null=True, verbose_name='CST Number')),
                ('gst', models.CharField(blank=True, max_length=255, null=True, verbose_name='GST Number')),
                ('phone_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone 1')),
                ('phone_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone 2')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('past_due_amount', models.FloatField(default=0, verbose_name='Past Due Amount')),
                ('credit_amount', models.FloatField(default=0, verbose_name='Credit Amount')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fax Number')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Customer Code')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Lock Status')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Name')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(max_length=50, verbose_name='Category Name')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Discount (%)')),
                ('type', models.CharField(blank=True, choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], max_length=50, null=True, verbose_name='Type')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_discounts', to='product.brand', verbose_name='Brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_discounts', to='company.company', verbose_name='Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer_type', models.CharField(choices=[('distributor', 'Distributor'), ('retail', 'Retail'), ('wholesale', 'Wholesale')], max_length=20, verbose_name='Customer Type')),
                ('price_level', models.CharField(max_length=30, verbose_name='Price Level Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_pricelevel', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('replace_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Replace ID')),
                ('return_type', models.CharField(choices=[('credit', 'Credit'), ('settlement', 'Settlement')], max_length=25, verbose_name='Return Type')),
                ('settlement_pending', models.BooleanField(default=False, verbose_name='Settlement Pending')),
                ('settlement_completed', models.BooleanField(default=False, verbose_name='Settlement Completed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created BY')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_customers', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_orders', to='order.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('zone_code', models.CharField(max_length=50, verbose_name='Zone Code')),
                ('zone_description', models.TextField(blank=True, null=True, verbose_name='Zone Description')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_zone', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('route_name', models.CharField(max_length=50, verbose_name='Route Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesroute_company', to='company.company')),
                ('customer', models.ManyToManyField(blank=True, null=True, related_name='salesroute_customer', to='customers.customer')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplacementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('replace_quantity', models.PositiveIntegerField(verbose_name='Replace Quantity')),
                ('order_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_order_products', to='order.orderedproduct')),
                ('replacement_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_order_products', to='customers.replacement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceLevelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit_type', models.CharField(choices=[('box', 'Box'), ('case', 'Case'), ('piece', 'Piece')], default='piece', max_length=7, verbose_name='Unit Type')),
                ('custom_price', models.FloatField(verbose_name='Custom Price')),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelevel', to='customers.pricelevel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('receive_date', models.DateField(default=datetime.date.today, verbose_name='Receive Date')),
                ('entry_date', models.DateField(default=datetime.date.today, verbose_name='Entry Date')),
                ('receive_amount', models.FloatField(default=0.0, verbose_name='Receive Amount')),
                ('payment_mode', models.CharField(choices=[('check', 'Cheque'), ('cash', 'Cash'), ('upi/neft/rtgs', 'UPI/NEFT/RTGS')], default='cash', max_length=30, verbose_name='Payment Mode')),
                ('check_no', models.IntegerField(blank=True, null=True, verbose_name='Check No')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Id')),
                ('remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='Remark')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_customer', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleVendorDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('primary_percent', models.FloatField(blank=True, default=0, null=True, verbose_name='Primary Discount (%)')),
                ('additional_percent', models.FloatField(blank=True, default=0, null=True, verbose_name='Additional Discount (%)')),
                ('is_primary_brand_discount', models.BooleanField(default=False, verbose_name='Is Primary Brand Discount')),
                ('is_secondary_brand_discount', models.BooleanField(default=False, verbose_name='Is Secondary Brand Discount')),
                ('additional_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_secondary_discounts', to='customers.discount')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='product.brand', verbose_name='Brand')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='customers.customer', verbose_name='Customer')),
                ('primary_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_primary_discounts', to='customers.discount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('store', 'Store'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=255, null=True, verbose_name='Type')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile No')),
                ('is_default', models.BooleanField(default=False, verbose_name='is Default')),
                ('customer_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('shipping_address_line_1', models.CharField(max_length=255, verbose_name='Address line 1')),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2')),
                ('shipping_suite_apartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 3')),
                ('shipping_city', models.CharField(max_length=255, verbose_name='City')),
                ('shipping_state', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='State')),
                ('shipping_country', models.CharField(default='INDIA', max_length=255, verbose_name='Country')),
                ('shipping_zip_code', models.IntegerField(blank=True, null=True, verbose_name='Zip Code')),
                ('shipping_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('shipping_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('is_default', models.BooleanField(default=False, verbose_name='is Default')),
                ('shipping_address_line_3', models.CharField(blank=True, max_length=2550, null=True, verbose_name='Address line 3')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shipping_address', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('customer_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bill', to='order.orderbill', verbose_name='Order Bill')),
                ('customer_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='customers.payment', verbose_name='Customer Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.TextField(verbose_name='Remark')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Action By')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Document Name')),
                ('document', models.FileField(upload_to='customer documents', validators=[app_modules.customers.validators.validate_file_extension])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('billing_address_line_1', models.CharField(max_length=255, verbose_name='Address line 1')),
                ('billing_address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2')),
                ('billing_suite_apartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 3')),
                ('billing_city', models.CharField(max_length=255, verbose_name='City')),
                ('billing_state', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='State')),
                ('billing_country', models.CharField(default='INDIA', max_length=255, verbose_name='Country')),
                ('billing_zip_code', models.IntegerField(blank=True, null=True, verbose_name='Zip Code')),
                ('billing_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('billing_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('is_default', models.BooleanField(default=False, verbose_name='is Default')),
                ('billing_address_line_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 3')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_billing_address', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50, verbose_name='Status')),
                ('bill_amount', models.FloatField(default=0.0, verbose_name='Bill Amount')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='Paid Amount')),
                ('due_amount', models.FloatField(default=0.0, verbose_name='Due Amount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bill', to='customers.customer', verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='price_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_level_customer', to='customers.pricelevel'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.zone', verbose_name='Zone'),
        ),
    ]
