# Generated by Django 4.1.7 on 2024-09-19 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('address_line_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('latitude', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Longitude')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company-logo', verbose_name='Company Logo')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address_line_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('latitude', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
